[workspace]
resolver = "2"
members = [
	"foobar"
]

# These settings will apply to all members of the workspace that opt in to them
[workspace.package]
version = "0.0.0"
license = "MIT-0 OR Apache-2.0"
repository = "https://github.com/NexusSocial/social"
edition = "2024"
rust-version = "1.86.0"
